/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Autoscroll: typeof import('./src/components/autoscroll.vue')['default']
    Destaques: typeof import('./src/components/destaques.vue')['default']
    Footer: typeof import('./src/components/NavFooter.vue')['default']
    Home: typeof import('./src/components/Home.vue')['default']
    NavFooter: typeof import('./src/components/NavFooter.vue')['default']
    NavHeader: typeof import('./src/components/NavHeader.vue')['default']
    Preloader: typeof import('./src/components/Preloader.vue')['default']
    Programa: typeof import('./src/components/programa.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VLibras: typeof import('./src/components/VLibras.vue')['default']
  }
}
