/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/acessibilidade': RouteRecordInfo<'/acessibilidade', '/acessibilidade', Record<never, never>, Record<never, never>>,
    '/atracoes': RouteRecordInfo<'/atracoes', '/atracoes', Record<never, never>, Record<never, never>>,
    '/faq': RouteRecordInfo<'/faq', '/faq', Record<never, never>, Record<never, never>>,
    '/fotos': RouteRecordInfo<'/fotos', '/fotos', Record<never, never>, Record<never, never>>,
    '/mapa': RouteRecordInfo<'/mapa', '/mapa', Record<never, never>, Record<never, never>>,
    '/programacao': RouteRecordInfo<'/programacao', '/programacao', Record<never, never>, Record<never, never>>,
    '/servicos': RouteRecordInfo<'/servicos', '/servicos', Record<never, never>, Record<never, never>>,
  }
}
